# Generated by Django 3.1.14 on 2022-01-03 20:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectworkspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkspaceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(blank=True, default='', help_text='Workspace name. Must be between 3 and 50 characters long.', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)], verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AlterField(
            model_name='projectworkspace',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace ID', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='projects.projectworkspacelist'),
        ),
    ]
