# Generated by Django 3.1.14 on 2022-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211010_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_project',
            field=models.TextField(null=True),
        ),
    ]
